name: Build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: [self-hosted, Linux, X64, luna, java]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java 21 Zulu
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Add Gralew permissions
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean shadowJar

      - name: Release
        uses: anton-yurchenko/git-release@ec9c5b5c36b27eaffc628785b9183eae54601200 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/libs/*.jar